version: '3.8'
services:
  postgres-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_USER=marco'
      - 'POSTGRES_PASSWORD=pass'
    ports:
      - '5433:5432'